user_dir: "/home/azureuser"
app_port: 8000
service:
  workingdir: /home/azureuser/newproject/myproject
  execstart: /home/azureuser/newproject/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 myproject.wsgi:application
djangoservice:
  workingdir: /home/azureuser/newproject/myproject
  execstart: /home/azureuser/newproject/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 myproject.wsgi:application


app:
  env:
    SQLALCHEMY_DATABASE_URI: postgresql://demouser:pass123@db01/demodb
    SQLALCHEMY_TRACK_MODIFICATIONS: False
    SECRET_KEY: sfvgbrh212131

django:
  env:
    SECRET_KEY: 'sfvgbrh212131'
    DATABASE_URL: 'postgresql://demouser:pass123@db01/demodb'
