---
- hosts: deploy-vm-2

  vars:
    app_dir: "{{user_dir}}/newproject"

  tasks:

  - name: docker compose build
    shell : "cd {{app_dir}} && docker-compose build"

    name: docker compose up
    shell : "cd {{app_dir}} && docker-compose up"
